# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('department_abbreviation', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=50)),
                ('lab', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
                ('final', models.CharField(max_length=25)),
                ('semester', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('nameID', models.IntegerField()),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
