# Generated by Django 2.0.5 on 2018-05-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180518_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='secitons',
            new_name='sections',
        ),
    ]
