# Generated by Django 2.0.5 on 2018-05-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20180518_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('interesting', models.PositiveSmallIntegerField()),
                ('hours_per_week_of_homework', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='course', to='courses.SectionInfo'),
        ),
    ]
