# Generated by Django 2.0.5 on 2018-05-19 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180519_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Review'),
        ),
    ]
