# Generated by Django 2.0.5 on 2018-05-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseinfo_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInfo'),
        ),
    ]
